---
- name: Deploy Flask Application
  hosts: "{{target_servers}}"
  gather_facts: no
  become: yes
  tasks:
    - name: Ensure Python 3 is installed
      become: yes
      apt:
        update_cache: true
        name:
        - python3
        - python3-pip
        state: present

    - name: Copy application files to server
      copy:
        src: ../../flask_app
        dest: /opt/

    - name: Create stage specific dotenv file.
      template:
        src: templates/flask.dotenv.j2
        dest: /opt/flask_app/.env

    - name: Ensure required Python packages from requirements.txt are installed
      become: yes
      pip:
        requirements: /opt/flask_app/requirements.txt
        state: present

    - name: Correct owner of files.
      become: yes
      command: "chown -R ubuntu: /opt/flask_app"

    - name: Correct permissions of files.
      become: yes
      command: "chmod -R 755 /opt/flask_app"
      changed_when: True
      notify: restart_flask

  handlers:
    - name: restart_flask
      become_user: ubuntu
      command: "sudo service flask restart"