---
- name: Provision Application Server
  hosts: "{{target_servers}}"
  gather_facts: no
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Python 3 is installed
      become: yes
      apt:
        name: python3
        state: present

    - name: Ensure Python 3 pip is installed
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Create log directory for Flask application
      file:
        path: /var/log/flask
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy application files to server
      copy:
        src: ../../flask_app
        dest: /opt

    - name: Install required Python packages from requirements.txt
      become: yes
      pip:
        requirements: /opt/flask_app/requirements.txt
        state: present

    - name: Create systemd service file for Flask application
      template:
        src: templates/flask.systemd.service.j2
        dest: /etc/systemd/system/flask.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Flask application service
      systemd:
        name: flask
        state: started
        enabled: yes
