---
- name: Provision Database Server
  hosts: "{{target_servers}}"
  gather_facts: no
  become: yes
  vars:
    mongo_uri_localhost: "mongodb://localhost:27017/"
    mongod_version: ["0.0.0"]
  tasks:
    - name: Check if MongoDB is already installed
      command: which mongod
      register: mongod_installed
      ignore_errors: yes

    - name: Validate existing mongod version
      block:
        - name: Get MongoDB version
          command: mongod --version
          register: mongod_version_response
          ignore_errors: yes

        - name: Set mongo_version_output variables
          set_fact:
            mongod_version_output: "{{mongod_version_response | default('version_not_found')}}"

        - name: Parse MongoDB version
          set_fact:
            mongod_version: "{{ mongod_version_output.stdout | regex_search('db version v([0-9.]+)', '\\1') | default(['version_not_found'])}}"
          when: mongod_version_output is defined

        - name: Check MongoDB version
          debug:
            msg: "Installed MongoDB version: {{ mongod_version }}"

        - name: Confirm correct MongoDB version
          debug:
            msg: "Correct MongoDB version (4.4.29) is installed."
          when: mongod_version[0] == "4.4.29"

        - name: Print MongoDB version is incorrect
          debug:
            msg: "Wrong MongoDB version installed: {{ mongod_version[0] }}. Expected version: 4.4.29"
          when: mongod_version[0] != "4.4.29"
      when: mongod_installed.stdout != ""

    - name: MongoDB incorrect version removal and installation of expected version.
      block:
        - name: Remove native mongodb provided by Ubuntu.
          command: sudo apt-get purge -y mongo*

        - name: Remove native mongodb provided by Ubuntu.
          command: sudo rm -rf /var/log/mongodb /var/lib/mongodb

        - name: Install required packages for mongodb
          apt:
            name:
              - gnupg
              - curl
            state: present

        - name: Add MongoDB repository key
          apt_key:
            url: https://www.mongodb.org/static/pgp/server-4.4.asc
            keyring: /usr/share/keyrings/mongodb-server-4.4.gpg
            state: present

        - name: Add MongoDB repository to sources list
          apt_repository:
            repo: deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
            state: present

        - name: Install Mongodb
          apt:
            update_cache: true
            name:
            - mongodb-org=4.4.29
            - mongodb-org-server=4.4.29
            - mongodb-org-shell=4.4.29
            - mongodb-org-mongos=4.4.29
            - mongodb-org-tools=4.4.29
      when: mongod_version[0] != "4.4.29"

    - name: Ensure MongoD is running and enabled
      systemd:
        name: mongod
        enabled: yes
        state: started

    - name: Configure MongoDB to allow remote connections
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  bindIp:.*'
        line: '  bindIp: 0.0.0.0'
        state: present
        backrefs: yes

    - name: Correct permissions for mongod service
      command: "sudo chown -R mongodb: /var/lib/mongodb/ /tmp/mongodb-27017.sock"
      notify: restart_mongodb

    - name: Create mongodb database and collection
      command: mongo mongodb://localhost:27017/web --eval "db.getCollectionNames().indexOf('customers') === -1 && db.createCollection('customers')"

  handlers:
    - name: restart_mongodb
      become: true
      systemd:
        name: mongod
        state: restarted
